[package]
name = "gatekeeper"
version = "0.1.0"
authors = ["Blake Loring <blake_l@parsed.uk>"]

[dependencies]
mio = "*"
log = "*"
env_logger = "*"
rustc-serialize = "*"

[dependencies.world_lib]
path = "../WorldLib/"